ZAP/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cuentas.urls', namespace="cuenta")),
]

cuentas/urls.py
from django.conf.urls import url
from cuentas.views import LoginDir, Registro, Logout, Sesion

urlpatterns = [
    url(r'^home/$', LoginDir.as_view(), name="home"),
    url(r'^Registro/$', Registro.as_view(), name="Registro"),
    url(r'^Logout/$', Logout.as_view(), name="Logout"),
    url(r'^sesion/$', Sesion.as_view(), name="sesion")
]

cuentas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Usuarios(models.Model):
    """docstring for telefono"""
    id_persona = models.OneToOneField(User)
    tel = models.IntegerField(null=True, blank=True)
    fecha = models. DateField(auto_now=False, auto_now_add=False)


class Tipnot(models.Model):
    """docstring for tip_not"""
    tipo = models.CharField(max_length=15, blank=False)


class Noticia(models.Model):
    """docstring for noticia"""
    id_persona = models.ForeignKey(User)
    id_tipo = models.ForeignKey(Tipnot)


class Amigo(models.Model):
    """docstring for Amigo"""
    usr1 = models.OneToOneField(User)
    usr2 = models.ManyToManyField('Amigo')

cuentas/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms

# Create the form class.


class RegisterForm(ModelForm):
    error_messages = {
        'password_mismatch': ("las contraseñas no coinciden"),
    }
    password1 = forms.CharField(label=("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("username", 'first_name', 'last_name', 'email')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

cuentas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from cuentas.forms import RegisterForm
from django.views.generic import TemplateView, ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth.models import User


class LoginDir(SuccessMessageMixin, FormView):
    form_class = AuthenticationForm
    template_name = "home.html"
    success_url = reverse_lazy("cuenta:sesion")
    success_message = "Welcome back %(username)s!"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            print(True)
            return redirect(self.get_success_url())
        else:
            print(False)
            return super(LoginDir, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginDir, self).form_valid(form)


class Registro(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = "registro.html"
    success_url = reverse_lazy("cuenta:home")
    success_message = "User was created successfully"


class Sesion(ListView):
    model = User
    template_name = "mainalt.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(Sesion, self).dispatch(self.request, *args, **kwargs)


class Logout(RedirectView):
    pattern_name = 'cuenta:home'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(Logout, self).get(request, *args, **kwargs)

templates/cuenta/home.html
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
<title>Zap!</title>
<head>
<style>

a{
	color: white;
	text-decoration: none;

}

table{
	padding-top: 250px;
}

input{
	width: 200px;
	height: 30px;
	border-color: #7acdff ;
	border-radius: 5px;
	-webkit-transition: width 0.5s;
}
input:hover{
	width: 220px;
}

div {
	border-radius: 5px;
	width: 180px;
    height: 30px;
    padding-top: 10px;
    padding-left: 10px;
    padding-right: 10px;
    background: #19a9ff;
    font-family: Verdana;
    -webkit-transition: width 2s, background-color 2s; /* For Safari 3.1 to 6.0 */
    transition: width 0.5s;
	
}
div:hover {
	background-color:#7acdff ;
	width: 210px;
	
}
div:active {
	position:relative;
	top:1px;
}



</style>
</head>
<body background="back3.png">

	<center><table>
		
			<tr>
				<td><img src="Zap.png"></td>
			</tr>
			
			<tr>
				<td align="center"><input placeholder="Usuario"></td>
			</tr>
			
			<tr>
				<td align="center"><input type="password" placeholder="Contraseña"></td>
			</tr>
			
			<tr>
				<td align="center"><a href="main.html"><div>Iniciar Sesión</div></a></td>
			</tr>

			<tr>
				<td align="center"><a href="registro.html"><div>Registrarse</div></a></td>
			</tr>
		
	</table></center>


</body>
</html>

templates/cuenta/mainalt.html
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
<head>
<style>

div#cont{
    background: #333;
    border-radius: 15px;
    width: 60%;
    height: 30%;
    margin-left: auto;
    margin-right: auto;
    padding-top: auto;
    padding-bottom: auto;
    color: #19a9ff;
    font-family: Verdana;
    
}
div#cont > img {
    margin-left: auto;
    margin-right: auto;
    margin-bottom: auto;
    margin-top: auto;
    
    
}

div#cont > img#pp {
    margin-left: 20px;
    margin-right: auto;
    padding-top: 2%;
    max-width: 15%;
    max-height: 15%;
    
    
}

div#cont > p {
    margin-left: 15%;
    margin-right: 15%;
    padding-top: 15%;
    
    
    color: #19a9ff;
    font-family: Verdana;
}

div#cont > input {
    margin-left: 20px;
    margin-bottom: 20px;
    width: 200px;
    height: 30px;
    border-color: #7acdff ;
    border-radius: 5px;
    -webkit-transition: width 0.5s;
}

div#cont > input:hover{
    width: 220px;
}

div#menu{ 
   
    padding-top: 2%;
    width: 90% ;
    margin-left: auto ;
    margin-right: auto;
    margin-bottom: 2%;

}

div#menu > a{
    font-family: Verdana;
    font-size:17px;
    background: #333;
    padding: 12px 24px;
    color:#19a9ff;
    
    text-decoration:none;
    border-radius: 5px;
    transition: background 0.3s linear 0s, color 0.3s linear 0s;
}

div#menu > a:hover{
    background: #7acdff;
    color:#333;
}

div#top {
    margin-left: 90%;
}

div#top > a{
    background: #333;
    border-radius: 15px;
    color: #19a9ff;
    text-decoration: none;
    padding: 12px 24px;
}

img {
    display: block;
    max-width: 95%;
    max-height: 95%;
    width: auto;
    height: auto;
    margin-right: auto;
    margin-left: auto;
    margin-top: auto;
    margin-bottom: auto;
}

div#User {
    margin-left: 20px;
    margin-right: auto;
    margin-bottom: 2%;
}

div#User > a{
    text-decoration: none;
    color:#19a9ff;
    
}

th{
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 10px;
}

th#pic > img#pp{

    max-width: 35%;
    max-height: 35%;
    padding-top: 2%;
    padding-bottom: 2%;
}

th#name {
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 50px;
}

</style>
</head>
<body background="back2.png">
    <header>
	<center><div id="menu">
    
    <a href="main.html">Newsfeed</a>
    <a href="mainalt.html">Perfil</a>
    <a href="#">Buscar</a>
    <a href="mensajes.html">Mensajes</a>
    <a href="home.html">Acerca De</a>
	</div></center>

	<center><div id="cont">

        <table cellpadding="10">
            <tr>
                <th id="pic"><img src="pp.jpg" id="pp"></th>
            </tr>
            <tr>
                <th id="name">Juan Pérez</th>
            </tr>
            <tr>
                <th> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,</th>
            </tr>

        </table>

    </div></center>
</header>



</body>
</html>

templates/cuentas/home.html
{% load static from staticfiles %}
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
<title>Zap!</title>
<head>
<style>

a{
	color: white;
	text-decoration: none;

}

table{
	padding-top: 250px;
}

input{
	width: 200px;
	height: 30px;
	border-color: #7acdff ;
	border-radius: 5px;
	-webkit-transition: width 0.5s;
}
input:hover{
	width: 220px;
}

div {
	border-radius: 5px;
	width: 180px;
    height: 30px;
    padding-top: 10px;
    padding-left: 10px;
    padding-right: 10px;
    background: #19a9ff;
    font-family: Verdana;
    -webkit-transition: width 2s, background-color 2s; /* For Safari 3.1 to 6.0 */
    transition: width 0.5s;
	
}
div:hover {
	background-color:#7acdff ;
	width: 210px;
	
}
div:active {
	position:relative;
	top:1px;
}



</style>
</head>
<body background="{% static "img/back3.png" %}">

<center><table><form method="POST">
    	{% csrf_token %}
<tr>
				<td><img src="{% static "img/ZAP.png" %}"></td>
			</tr>
			
<tr>
	<td>
		{{ form.username.errors}}
    	{{ form.username.label_tag}}
    	{{ form.username}}
	</td>

</tr>
<tr>
	<td>
		{{ form.password.errors}}
    	{{ form.password.label_tag}}
    	{{ form.password}}
	</td>
</tr>
<tr>
 	<td>
    	<input type="submit" value="iniciar sesion">
    </td>
</tr>
</form>
<tr>
	<td align="center"><a href="{% url 'cuenta:Registro' %}"><div>Registrarse</div></a></td>
</tr>
		
</table></center>


</body>
</html>

templates/cuentas/mainalt.html
{% load static from staticfiles %}
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
<head>
<style>

div#cont{
    background: #333;
    border-radius: 15px;
    width: 60%;
    height: 30%;
    margin-left: auto;
    margin-right: auto;
    padding-top: auto;
    padding-bottom: auto;
    color: #19a9ff;
    font-family: Verdana;
    
}
div#cont > img {
    margin-left: auto;
    margin-right: auto;
    margin-bottom: auto;
    margin-top: auto;
    
    
}

div#cont > img#pp {
    margin-left: 20px;
    margin-right: auto;
    padding-top: 2%;
    max-width: 15%;
    max-height: 15%;
    
    
}

div#cont > p {
    margin-left: 15%;
    margin-right: 15%;
    padding-top: 15%;
    
    
    color: #19a9ff;
    font-family: Verdana;
}

div#cont > input {
    margin-left: 20px;
    margin-bottom: 20px;
    width: 200px;
    height: 30px;
    border-color: #7acdff ;
    border-radius: 5px;
    -webkit-transition: width 0.5s;
}

div#cont > input:hover{
    width: 220px;
}

div#menu{ 
   
    padding-top: 2%;
    width: 90% ;
    margin-left: auto ;
    margin-right: auto;
    margin-bottom: 2%;

}

div#menu > a{
    font-family: Verdana;
    font-size:17px;
    background: #333;
    padding: 12px 24px;
    color:#19a9ff;
    
    text-decoration:none;
    border-radius: 5px;
    transition: background 0.3s linear 0s, color 0.3s linear 0s;
}

div#menu > a:hover{
    background: #7acdff;
    color:#333;
}

div#top {
    margin-left: 90%;
}

div#top > a{
    background: #333;
    border-radius: 15px;
    color: #19a9ff;
    text-decoration: none;
    padding: 12px 24px;
}

img {
    display: block;
    max-width: 95%;
    max-height: 95%;
    width: auto;
    height: auto;
    margin-right: auto;
    margin-left: auto;
    margin-top: auto;
    margin-bottom: auto;
}

div#User {
    margin-left: 20px;
    margin-right: auto;
    margin-bottom: 2%;
}

div#User > a{
    text-decoration: none;
    color:#19a9ff;
    
}

th{
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 10px;
}

th#pic > img#pp{

    max-width: 35%;
    max-height: 35%;
    padding-top: 2%;
    padding-bottom: 2%;
}

th#name {
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 50px;
}

</style>
</head>
<body background="{% static "img/back2.png" %}">
    <header>
	<center><div id="menu">
    
    <a href="main.html">Newsfeed</a>
    <a href="{% url 'cuenta:sesion' %}">Perfil</a>
    <a href="#">Buscar</a>
    <a href="mensajes.html">Mensajes</a>
    <a href="{% url 'cuenta:Logout' %}">salir</a>
	</div></center>

	<center><div id="cont">


        <table cellpadding="10">
            <tr>
                <th id="pic"><img src="pp.jpg" id="pp"></th>
            </tr>
            <tr>
                <th id="name">{{ user.username }} {{ user.first_name }} {{ user.last_name }}</th>
            </tr>
            <tr>
                <th> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,</th>
            </tr>

            <a href="{% url 'cuenta:cambio' %}">cambiar</a>

        </table>

    </div></center>
</header>



</body>
</html>

templates/cuentas/mainalt2.html
{% load static from staticfiles %}
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
<head>
<style>

div#cont{
    background: #333;
    border-radius: 15px;
    width: 60%;
    height: 30%;
    margin-left: auto;
    margin-right: auto;
    padding-top: auto;
    padding-bottom: auto;
    color: #19a9ff;
    font-family: Verdana;
    
}
div#cont > img {
    margin-left: auto;
    margin-right: auto;
    margin-bottom: auto;
    margin-top: auto;
    
    
}

div#cont > img#pp {
    margin-left: 20px;
    margin-right: auto;
    padding-top: 2%;
    max-width: 15%;
    max-height: 15%;
    
    
}

div#cont > p {
    margin-left: 15%;
    margin-right: 15%;
    padding-top: 15%;
    
    
    color: #19a9ff;
    font-family: Verdana;
}

div#cont > input {
    margin-left: 20px;
    margin-bottom: 20px;
    width: 200px;
    height: 30px;
    border-color: #7acdff ;
    border-radius: 5px;
    -webkit-transition: width 0.5s;
}

div#cont > input:hover{
    width: 220px;
}

div#menu{ 
   
    padding-top: 2%;
    width: 90% ;
    margin-left: auto ;
    margin-right: auto;
    margin-bottom: 2%;

}

div#menu > a{
    font-family: Verdana;
    font-size:17px;
    background: #333;
    padding: 12px 24px;
    color:#19a9ff;
    
    text-decoration:none;
    border-radius: 5px;
    transition: background 0.3s linear 0s, color 0.3s linear 0s;
}

div#menu > a:hover{
    background: #7acdff;
    color:#333;
}

div#top {
    margin-left: 90%;
}

div#top > a{
    background: #333;
    border-radius: 15px;
    color: #19a9ff;
    text-decoration: none;
    padding: 12px 24px;
}

img {
    display: block;
    max-width: 95%;
    max-height: 95%;
    width: auto;
    height: auto;
    margin-right: auto;
    margin-left: auto;
    margin-top: auto;
    margin-bottom: auto;
}

div#User {
    margin-left: 20px;
    margin-right: auto;
    margin-bottom: 2%;
}

div#User > a{
    text-decoration: none;
    color:#19a9ff;
    
}

th{
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 10px;
}

th#pic > img#pp{

    max-width: 35%;
    max-height: 35%;
    padding-top: 2%;
    padding-bottom: 2%;
}

th#name {
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 50px;
}

</style>
</head>
<body background="{% static "img/back2.png" %}">
    <header>
	<center><div id="menu">
    
    <a href="main.html">Newsfeed</a>
    <a href="{% url 'cuenta:sesion' %}">Perfil</a>
    <a href="#">Buscar</a>
    <a href="mensajes.html">Mensajes</a>
    <a href="{% url 'cuenta:Logout' %}">salir</a>
	</div></center>

	<center><div id="cont">


        <table cellpadding="10">
            <tr>
                <th id="pic"><img src="pp.jpg" id="pp"></th>
            </tr>
            <tr>
                <th id="name">{{ user.username }} {{ user.first_name }}{{ user.last_name }}</th>
            </tr>
            <tr>
                <th> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,</th>
            </tr>

        </table>

    </div></center>
</header>



</body>
</html>

templates/cuentas/mensajes.html
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<html>
<head>
<style>

div#cont{
    background: #333;
    border-radius: 15px;
    width: 30%;
    height: 30%;
    margin-left: auto;
    margin-right: auto;
    padding-top: auto;
    padding-bottom: auto;
    color: #19a9ff;
    font-family: Verdana;
    
}
div#cont > img {
    margin-left: auto;
    margin-right: auto;
    margin-bottom: auto;
    margin-top: auto;
    
    
}

div#cont > img#pp {
    margin-left: 20px;
    margin-right: auto;
    padding-top: 2%;
    max-width: 15%;
    max-height: 15%;
    
    
}

div#cont > p {
    margin-left: 15%;
    margin-right: 15%;
    padding-top: 15%;
    
    
    color: #19a9ff;
    font-family: Verdana;
}

div#cont > input {
    margin-left: 20px;
    margin-bottom: 20px;
    width: 200px;
    height: 30px;
    border-color: #7acdff ;
    border-radius: 5px;
    -webkit-transition: width 0.5s;
}

div#cont > input:hover{
    width: 220px;
}

div#menu{ 
   
    padding-top: 2%;
    width: 90% ;
    margin-left: auto ;
    margin-right: auto;
    margin-bottom: 2%;

}

div#menu > a{
    font-family: Verdana;
    font-size:17px;
    background: #333;
    padding: 12px 24px;
    color:#19a9ff;
    
    text-decoration:none;
    border-radius: 5px;
    transition: background 0.3s linear 0s, color 0.3s linear 0s;
}

div#menu > a:hover{
    background: #7acdff;
    color:#333;
}

div#top {
    margin-left: 90%;
}

div#top > a{
    background: #333;
    border-radius: 15px;
    color: #19a9ff;
    text-decoration: none;
    padding: 12px 24px;
}

img {
    display: block;
    max-width: 95%;
    max-height: 95%;
    width: auto;
    height: auto;
}

div#User {
    margin-left: 20px;
    margin-right: auto;
    margin-bottom: 2%;
}

div#User > a{
    text-decoration: none;
    color:#19a9ff;
    
}

th{
    margin-left: 20px;
    margin-right: none;
    max-width: 35%;
    max-height: 35%;
    width: auto;
    height: auto;
    padding-top: 2%;
    font-size: 10px;
}

th#pic > img#pp{

    max-width: 35%;
    max-height: 35%;
    padding-top: 2%;
    padding-bottom: 2%;
}

th#msg {
    
    font-size: 15px;
}

</style>
</head>
<body background="back2.png">
    <header>
	<center><div id="menu">
    
    <a href="main.html">Newsfeed</a>
    <a href="mainalt.html">Perfil</a>
    <a href="#">Buscar</a>
    <a href="mensajes.html">Mensajes</a>
    <a href="home.html">Acerca De</a>
	</div></center>

	<center><div id="cont">

        <table cellpadding="10">
            <col width="130">
            <col width="130">
            <tr>
                <th id="pic"><img src="pp2.jpg" id="pp"></th>
                <th id="msg">Hola! Cómo estás?</th>
            </tr>
            <tr>
                <th id="pic"><img src="pp2.jpg" id="pp"></th>
                <th id="msg">Me gustó tu cómic!</th>
            </tr>
            <tr>
                <th id="pic"><img src="pp2.jpg" id="pp"></th>
                <th id="msg">Lo vendes?</th>
            </tr>
        </table>

    </div></center>
</header>



</body>
</html>